add validation task definition file

diff --git a/.github/workflows/deploy-docker-ecs.yaml b/.github/workflows/deploy-docker-ecs.yaml
--- a/.github/workflows/deploy-docker-ecs.yaml
+++ b/.github/workflows/deploy-docker-ecs.yaml
@@ -30,6 +30,15 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ env.AWS_REGION }}
 
+      - name: Ensure ECS task definition file exists
+        run: |
+          if [ ! -f "${{ env.ECS_TASK_DEFINITION }}" ]; then
+            echo "❌ Task definition file not found at path: ${{ env.ECS_TASK_DEFINITION }}"
+            exit 1
+          else
+            echo "✅ Found ECS task definition at ${{ env.ECS_TASK_DEFINITION }}"
+          fi
+
       - name: Login to Amazon ECR
         id: login-ecr
         uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a
